require("defaultuser.plugins-setup")
require("defaultuser.core.options")
require("defaultuser.core.keymaps")
require("defaultuser.core.colorscheme")
require("defaultuser.plugins.comment")
require("defaultuser.plugins.nvim-tree")
require("defaultuser.plugins.lualine")
require("defaultuser.plugins.telescope")
require("defaultuser.plugins.nvim-cmp")
require("defaultuser.plugins.lsp.mason")
require("defaultuser.plugins.lsp.lspsaga")
require("defaultuser.plugins.lsp.lspconfig")
require("defaultuser.plugins.lsp.null-ls")
require("defaultuser.plugins.autopairs")
require("defaultuser.plugins.treesitter")
require("defaultuser.plugins.gitsigns")

